### ISSUE TITLE
metarnearby.php - shows offline

### ISSUE THREAD

**Issue by dive76** [weather34/Meteobridge-Beta#5]
Hi Brian,
Just tried the latest version. Looks great. Found that the metar shows "offline" and no data is pulled. Double checked the settings file and all looks good. Checking directly on the https://www.checkwx.com/weather/WSSL all looks ok. Please let me know in case you need any more information.

Best regards,

Lars
www.singaporeweather.info

**Comment by weather34** [comment]
your a brave man :-) 

your output from WSSL is delivering this only 

https://www.singaporeweather.info/jsondata/metar34.txt
`{"statusCode":429,"error":"Too Many Requests","message":"exceeded api rate limit for today"}`

so how is stationcron.php running is set for 30 minutes? do you have any other versions running i.e are you using the NANOSD internal dashboard  there is a known issue since last firmware update that is maxing out api CALLS seem to recall reading on the wxforum.net .

**Comment by dive76** [comment]
Always brave 😉 The trouble was caused by the internal dashboard.

**Comment by weather34** [comment]
ok no problem think its fixed in firmware release today.. ps dont think you have the charts setup correctly in meteobridge services . looks like you have step one ok but step two doesnt look like it is running. and i would set stationcron.php to run at every 30 minutes as any forecast data is generally only changed every 30 minutes to an hour by the providers sometimes longer..

step 1 setup storing todays data to a CSV file for today charts to read file is chartstoday.php

Goto meteobridge services screen

Goto Select new service

Select from the drop down menu HTTP Request

Select Perodical in the next menu

Click Save at the bottom of the screen

Now look for new HTTP request

select every FULL 10 MINUTES

NOW INSERT THE URL example

http(s)://weathersomething/chartstoday.php

now click save .
step 2 setup storing monthly yearly data to a CSV file for monthly/year charts to read file is charts-month-year.php

Goto meteobridge services screen

Goto Select new service

Select from the drop down menu HTTP Request

Select Specific Time in the next menu

Click Save at the bottom of the screen

Now look for new HTTP request

select 23:45 (its the nearest the meteobridge will allow you get to the end of the day)

NOW INSERT THE URL example

http(s)://weathersomething/charts-month-year.php

now click save .
thats it !!! no mysql to setup just these two files will do

**Comment by dive76** [comment]
The charts-month-year.php is actually in place. I had used the data files from the “normal” version and changed to tile to full month.
Could that cause an issue?

**Comment by weather34** [comment]
ok lars 

chart files from original version are not fully compatible . i would do a clean install and start a fresh , if you send me two files 2019.csv and Jun.csv from original i will convert them for you .send via email im here till tuesday ..after that no changes for quite sometime so if your happy how it works now then should be fine for a few months.

**Comment by dive76** [comment]
Please find attached. Thanks a lot for your great support.

**Comment by weather34** [comment]
morning lars or afternoon

i dont see attached and seriously do a fresh install and send the two files via normal email..brian

**Comment by dive76** [comment]
Agree. Start clean is best!

**Comment by weather34** [comment]
lars 

ive updated these files today there is a lot so now is the time todo a fresh install ,ive used your csv files from your site but you have some deep data spikes in yearly data :-) . that is the last update for this beta version for quite sometime now after tomorrow..

basically refined and fixed charts , aligned to correct csv fixed monthly creation of csv file and added new tooltips .hopefully useable but it is very critical to read the setup of charts and run stationcron.php every 30 minutes or 1 hour...

darksky forecast etc has been removed ...

 charts-month-year.php
 chartstoday.php

weather34charts/todayrainfall.php
weather34charts/todayrainfallmedium.php
weather34charts/todayrainfallsmall.php
 weather34charts/monthlydewpoint.php
weather34charts/monthlydewpointsmall.php
weather34charts/monthlytemperature.php
weather34charts/monthlytemperaturesmall.php
weather34charts/todaydewmedium.php
weather34charts/todaydewpointsmall.php
weather34charts/todaytemperature.php
weather34charts/todaytempmedium.php
weather34charts/todaytempsmall.php
weather34charts/yearlydewpointprevious.php
weather34charts/yearlydewpointsmall.php
weather34charts/yearlydewpointsmall2018.php
weather34charts/yearlytemperature.php
weather34charts/yearlytemperaturemedium.php
weather34charts/yearlytemperatureprevious.php
weather34charts/yearlytemperaturesmall.php
weather34charts/yearlytemperaturesmall2018.php

easyweathersetup.php
index.php
rainfall.php
temperature.php
temperaturein.php
weather34uvsolar.php

 css/weather34dashboard.dark.css
css/weather34dashboard.light.css

**Comment by dive76** [comment]
Great Brian, will do an update tomorrow. Thanks a lot.




On Tue, Jul 9, 2019 at 10:32 PM +0530, "brian underdown" <notifications@github.com<mailto:notifications@github.com>> wrote:


lars

ive updated these files today there is a lot so now is the time todo a fresh install ,ive used your csv files from your site but you have some deep data spikes in yearly data :-) . that is the last update for this beta version for quite sometime now after tomorrow..

basically refined and fixed charts , aligned to correct csv fixed monthly creation of csv file and added new tooltips .hopefully useable but it is very critical to read the setup of charts and run stationcron.php every 30 minutes or 1 hour...

darksky forecast etc has been removed ...

charts-month-year.php
chartstoday.php

weather34charts/todayrainfall.php
weather34charts/todayrainfallmedium.php
weather34charts/todayrainfallsmall.php
weather34charts/monthlydewpoint.php
weather34charts/monthlydewpointsmall.php
weather34charts/monthlytemperature.php
weather34charts/monthlytemperaturesmall.php
weather34charts/todaydewmedium.php
weather34charts/todaydewpointsmall.php
weather34charts/todaytemperature.php
weather34charts/todaytempmedium.php
weather34charts/todaytempsmall.php
weather34charts/yearlydewpointprevious.php
weather34charts/yearlydewpointsmall.php
weather34charts/yearlydewpointsmall2018.php
weather34charts/yearlytemperature.php
weather34charts/yearlytemperaturemedium.php
weather34charts/yearlytemperatureprevious.php
weather34charts/yearlytemperaturesmall.php
weather34charts/yearlytemperaturesmall2018.php

easyweathersetup.php
index.php
rainfall.php
temperature.php
temperaturein.php
weather34uvsolar.php

css/weather34dashboard.dark.css
css/weather34dashboard.light.css

**Comment by dive76** [comment]
Install newest version. Found one bug so far. Will open a new topic for it.
